#!/bin/bash

src=$1
source ./env_erp.sh
# not for ERP cluster at CCI
# source ./env.bgrs.sh
#BOOST_LIBRARYDIR=$LD_LIBRARY_PATH
#echo BOOST_LIBRARYDIR=$BOOST_LIBRARYDIR
#NETCDF=$NETCDF_ROOT
#NETCDF_CXX4_ROOT

#cmake \
 #   -DCUDA_NVCC_FLAGS="-arch=sm_70" \
 #   -DTHRUST_INCLUDE_DIR=$CUDA_PATH/include \
 #   -DNETCDF_DIR=$NETCDF \
 #   -DNETCDF_CXX_ROOT=$NETCDFCXX4 \
 #   -DNETCDF_LIBRARIES=$NETCDFDIR \
 #   -DNETCDF_INCLUDE_DIRS=$NETCDFINCLUDE \
 #   -DNETCDF_CXX_INCLUDE_DIR=$NETCDFCXX4INCLUDE \
 #   -DLIBCONFIGPP_INCLUDE_DIR=$LIBCONFIGPPINCLUDE \
 #   -DLIBCONFIGPP_LIBRARY=$LIBCONFIGPPLIB/libconfig++.so \
 #   -DLIBCONFIGPP_LIBRARIES=$LIBCONFIGPPLIB/libconfig++.so \
 #   -DBoost_DEBUG=OFF \
 #   -DBOOST_LIBRARYDIR=$BOOST_LIBRARYDIR \
 #   -DBoost_LIBRARIES=$Boost_LIBRARIES_LIST \
export  NETCDFLIB=netcdf 
export  NETCDFLIB_CPP=netcdf_c++4

 
cmake \
   -DNETCDF_CXX_LIBRARIES=$NETCDF_CXX4_ROOT/lib \
   -DNETCDF_DIR=$NETCDF_ROOT \
   -DNETCDF_LIBRARIES=$LD_LIBRARY_PATH \
   -DNETCDF_INCLUDE_DIRS=$NETCDF_ROOT/include \
   -DNETCDF_CXX_ROOT=$NETCDF_CXX4_ROOT \
   -DNETCDF_CXX_INCLUDE_DIR=$NETCDF_CXX4_ROOT/include \
    -DUSE_CUDA=0 \
    -DUSEMPI=0 \
    -DUSE_MPI=1 \
    -DUSE_OPENMP=1 \
    -DUSE_BOOST=1 \
    -DUSEIONIZATION=1 \
    -DUSERECOMBINATION=1 \
    -DUSEPERPDIFFUSION=0 \
    -DUSEPARDIFFUSION=0 \
    -DUSECOULOMBCOLLISIONS=0 \
    -DUSEFRICTION=0 \
    -DUSEANGLESCATTERING=0 \
    -DUSEHEATING=0 \
    -DUSETHERMALFORCE=0 \
    -DUSESURFACEMODEL=0 \
    -DUSESHEATHEFIELD=1 \
    -DBIASED_SURFACE=1 \
    -DUSEPRESHEATHEFIELD=1 \
    -DBFIELD_INTERP=0 \
    -DLC_INTERP=0 \
    -DGENERATE_LC=0 \
    -DEFIELD_INTERP=0 \
    -DPRESHEATH_INTERP=0 \
    -DDENSITY_INTERP=2 \
    -DTEMP_INTERP=2 \
    -DFLOWV_INTERP=0 \
    -DGRADT_INTERP=0 \
    -DODEINT=0 \
    -DFIXEDSEEDS=0 \
    -DPARTICLESEEDS=1 \
    -DGEOM_TRACE=0 \
    -DGEOM_HASH=2 \
    -DGEOM_HASH_SHEATH=2 \
    -DPARTICLE_TRACKS=1 \
    -DPARTICLE_SOURCE_SPACE=0 \
    -DPARTICLE_SOURCE_ENERGY=0 \
    -DPARTICLE_SOURCE_ANGLE=0 \
    -DPARTICLE_SOURCE_FILE=1 \
    -DSPECTROSCOPY=0 \
    -DUSE3DTETGEOM=1 \
    -DFLUX_EA=1 \
    -DUSECYLSYMM=1 \
    -DUSEFIELDALIGNEDVALUES=0 \
    -DFORCE_EVAL=1 \
    -DCHECK_COMPATIBILITY=1 \
    -DUSE_SORT=0 \
    $src
    #-DMANUAL_FLAGS={$USECUDA_ $USEMPI_ $USEBOOST_ $USEIONIZATION_} \
    #-DMANUAL_FLAGS="-DUSEIONIZATION=1" \
#~/cmake/cmake-3.7.0-rc1-Linux-x86_64/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DTHRUST_INCLUDE_DIR=$CUDA_PATH/include -DNETCDF_DIR=$NETCDF -DNETCDF_CXX_ROOT=$NETCDFCXX4 -DLIBCONFIGPP_LIBRARY=$LIBCONFIGDIR/$LIBCONFIGLIB  ..
