#!/bin/bash

src=$1
source ./env_gitr_blockade.sh

export  NETCDFLIB=netcdf 
export  NETCDFLIB_CPP=libnetcdf-cxx4.so
NETCDF_CXX4_ROOT=$NetCDF_PREFIX
libconfig=/lore/gopan/install/libconfig-1.7.2/install
# -DCUDA_NVCC_FLAGS="-arch=sm_70" \

cmake \
   -DLIBCONFIGPP_INCLUDE_DIR=$libconfig/include \
   -DLIBCONFIGPP_LIBRARY=$libconfig/lib/libconfig++.so \
   -DLIBCONFIGPP_LIBRARIES=$libconfig/lib/libconfig++.so \
   -DTHRUST_INCLUDE_DIR=$THRUST_INCLUDE_DIR \
   -DNETCDF_CXX_LIBRARIES=$NETCDF_CXX4_ROOT/lib64/$NETCDFLIB_CPP \
   -DNETCDF_INCLUDE_DIRS=$NETCDF_ROOT/include \
   -DNETCDF_CXX_INCLUDE_DIR=$NETCDF_CXX4_ROOT/include \
    -DUSE_CUDA=1 \
    -DUSEMPI=0 \
    -DUSE_MPI=1 \
    -DUSE_OPENMP=0 \
    -DUSE_BOOST=0 \
    -DUSEIONIZATION=1 \
    -DUSERECOMBINATION=1 \
    -DUSEPERPDIFFUSION=1 \
    -DUSEPARDIFFUSION=0 \
    -DUSECOULOMBCOLLISIONS=1 \
    -DUSEFRICTION=1 \
    -DUSEANGLESCATTERING=1 \
    -DUSEHEATING=1 \
    -DUSETHERMALFORCE=0 \
    -DUSESURFACEMODEL=1 \
    -DUSESHEATHEFIELD=1 \
    -DBIASED_SURFACE=1 \
    -DUSEPRESHEATHEFIELD=1 \
    -DBFIELD_INTERP=0 \
    -DLC_INTERP=0 \
    -DGENERATE_LC=0 \
    -DEFIELD_INTERP=0 \
    -DPRESHEATH_INTERP=0 \
    -DDENSITY_INTERP=2 \
    -DTEMP_INTERP=2 \
    -DFLOWV_INTERP=0 \
    -DGRADT_INTERP=0 \
    -DODEINT=0 \
    -DFIXEDSEEDS=0 \
    -DPARTICLESEEDS=1 \
    -DGEOM_TRACE=0 \
    -DGEOM_HASH=2 \
    -DGEOM_HASH_SHEATH=2 \
    -DPARTICLE_TRACKS=1 \
    -DPARTICLE_SOURCE_SPACE=0 \
    -DPARTICLE_SOURCE_ENERGY=0 \
    -DPARTICLE_SOURCE_ANGLE=0 \
    -DPARTICLE_SOURCE_FILE=1 \
    -DSPECTROSCOPY=3 \
    -DUSE3DTETGEOM=1 \
    -DFLUX_EA=1 \
    -DUSECYLSYMM=1 \
    -DUSEFIELDALIGNEDVALUES=0 \
    -DFORCE_EVAL=0 \
    -DCHECK_COMPATIBILITY=1 \
    -DUSE_SORT=0 \
    $src
    #-DMANUAL_FLAGS={$USECUDA_ $USEMPI_ $USEBOOST_ $USEIONIZATION_} \
    #-DMANUAL_FLAGS="-DUSEIONIZATION=1" \
#~/cmake/cmake-3.7.0-rc1-Linux-x86_64/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DTHRUST_INCLUDE_DIR=$CUDA_PATH/include -DNETCDF_DIR=$NETCDF -DNETCDF_CXX_ROOT=$NETCDFCXX4 -DLIBCONFIGPP_LIBRARY=$LIBCONFIGDIR/$LIBCONFIGLIB  ..
